#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: App\Controller\Api\AuthController::register
    methods: POST

login:
    path: /login_check
    methods:  POST

api:
    path: /api

web:
    path: /web
